name: Auto-approve PRs
on:
  pull_request:
    types: [opened, reopened]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
